# Generated by Django 3.2.19 on 2023-07-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipies',
            name='category',
            field=models.CharField(choices=[('ci_bu', 'Cinnamon Bun'), ('da_pa', 'Danish Pastry'), ('ce_ca', 'Cheese Cake'), ('ch_ca', 'Chocolate Cake'), ('cr_ca', 'Cream Cake'), ('st_ca', 'Strawberry Cake'), ('ea_me', 'Eaton Mess'), ('ap_pi', 'Apple Pie'), ('co_ki', 'Cookies'), ('ea_me', 'Eaton Mess'), ('br_ee', 'Brulee'), ('ic_cr', 'Ice Cream'), ('br_ie', 'Brownie'), ('pa_es', 'Pancakes'), ('mu_ns', 'Muffins'), ('ti_su', 'Tiramisu'), ('tr_le', 'Trifle')], default='co_ki', max_length=15),
            preserve_default=False,
        ),
    ]
