# Generated by Django 3.2.19 on 2023-06-28 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bulle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipies',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='recipies',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
