# Generated by Django 3.2.19 on 2023-06-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulle', '0002_auto_20230628_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
