# Generated by Django 3.2.19 on 2023-07-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulle', '0003_recipies_allergy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipies',
            name='allergy',
            field=models.CharField(blank=True, choices=[('dy', 'Dairy allergy'), ('nu', 'Nut allergy'), ('wt', 'Wheat allergy'), ('eg', 'Egg allergy'), ('sn', 'Soybean allergy'), ('or', 'Other')], max_length=15),
        ),
    ]
